// Auto-generated by scripts/prepare-backdrops.mjs — do not edit manually.

export interface BackdropFormatSources {
  640: string;
  1280: string;
  1920: string;
}

export interface BackdropAssetEntry {
  key: string;
  objectPosition: string;
  placeholder: boolean;
  avif: BackdropFormatSources;
  webp: BackdropFormatSources;
  jpg: BackdropFormatSources;
}

export const BACKDROP_ASSETS: Record<string, BackdropAssetEntry> = {
  'auth': {
    key: 'auth',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./auth-640.avif', import.meta.url).href,
      1280: new URL('./auth-1280.avif', import.meta.url).href,
      1920: new URL('./auth-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./auth-640.webp', import.meta.url).href,
      1280: new URL('./auth-1280.webp', import.meta.url).href,
      1920: new URL('./auth-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./auth-640.jpg', import.meta.url).href,
      1280: new URL('./auth-1280.jpg', import.meta.url).href,
      1920: new URL('./auth-1920.jpg', import.meta.url).href,
    },
  },
  'auth-recovery': {
    key: 'auth-recovery',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./auth-recovery-640.avif', import.meta.url).href,
      1280: new URL('./auth-recovery-1280.avif', import.meta.url).href,
      1920: new URL('./auth-recovery-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./auth-recovery-640.webp', import.meta.url).href,
      1280: new URL('./auth-recovery-1280.webp', import.meta.url).href,
      1920: new URL('./auth-recovery-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./auth-recovery-640.jpg', import.meta.url).href,
      1280: new URL('./auth-recovery-1280.jpg', import.meta.url).href,
      1920: new URL('./auth-recovery-1920.jpg', import.meta.url).href,
    },
  },
  'dashboard': {
    key: 'dashboard',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./dashboard-640.avif', import.meta.url).href,
      1280: new URL('./dashboard-1280.avif', import.meta.url).href,
      1920: new URL('./dashboard-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./dashboard-640.webp', import.meta.url).href,
      1280: new URL('./dashboard-1280.webp', import.meta.url).href,
      1920: new URL('./dashboard-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./dashboard-640.jpg', import.meta.url).href,
      1280: new URL('./dashboard-1280.jpg', import.meta.url).href,
      1920: new URL('./dashboard-1920.jpg', import.meta.url).href,
    },
  },
  'batches': {
    key: 'batches',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./batches-640.avif', import.meta.url).href,
      1280: new URL('./batches-1280.avif', import.meta.url).href,
      1920: new URL('./batches-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./batches-640.webp', import.meta.url).href,
      1280: new URL('./batches-1280.webp', import.meta.url).href,
      1920: new URL('./batches-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./batches-640.jpg', import.meta.url).href,
      1280: new URL('./batches-1280.jpg', import.meta.url).href,
      1920: new URL('./batches-1920.jpg', import.meta.url).href,
    },
  },
  'fefo': {
    key: 'fefo',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./fefo-640.avif', import.meta.url).href,
      1280: new URL('./fefo-1280.avif', import.meta.url).href,
      1920: new URL('./fefo-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./fefo-640.webp', import.meta.url).href,
      1280: new URL('./fefo-1280.webp', import.meta.url).href,
      1920: new URL('./fefo-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./fefo-640.jpg', import.meta.url).href,
      1280: new URL('./fefo-1280.jpg', import.meta.url).href,
      1920: new URL('./fefo-1920.jpg', import.meta.url).href,
    },
  },
  'inspections': {
    key: 'inspections',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./inspections-640.avif', import.meta.url).href,
      1280: new URL('./inspections-1280.avif', import.meta.url).href,
      1920: new URL('./inspections-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./inspections-640.webp', import.meta.url).href,
      1280: new URL('./inspections-1280.webp', import.meta.url).href,
      1920: new URL('./inspections-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./inspections-640.jpg', import.meta.url).href,
      1280: new URL('./inspections-1280.jpg', import.meta.url).href,
      1920: new URL('./inspections-1920.jpg', import.meta.url).href,
    },
  },
  'dispatch': {
    key: 'dispatch',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./dispatch-640.avif', import.meta.url).href,
      1280: new URL('./dispatch-1280.avif', import.meta.url).href,
      1920: new URL('./dispatch-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./dispatch-640.webp', import.meta.url).href,
      1280: new URL('./dispatch-1280.webp', import.meta.url).href,
      1920: new URL('./dispatch-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./dispatch-640.jpg', import.meta.url).href,
      1280: new URL('./dispatch-1280.jpg', import.meta.url).href,
      1920: new URL('./dispatch-1920.jpg', import.meta.url).href,
    },
  },
  'qr': {
    key: 'qr',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./qr-640.avif', import.meta.url).href,
      1280: new URL('./qr-1280.avif', import.meta.url).href,
      1920: new URL('./qr-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./qr-640.webp', import.meta.url).href,
      1280: new URL('./qr-1280.webp', import.meta.url).href,
      1920: new URL('./qr-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./qr-640.jpg', import.meta.url).href,
      1280: new URL('./qr-1280.jpg', import.meta.url).href,
      1920: new URL('./qr-1920.jpg', import.meta.url).href,
    },
  },
  'trace-public': {
    key: 'trace-public',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./trace-public-640.avif', import.meta.url).href,
      1280: new URL('./trace-public-1280.avif', import.meta.url).href,
      1920: new URL('./trace-public-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./trace-public-640.webp', import.meta.url).href,
      1280: new URL('./trace-public-1280.webp', import.meta.url).href,
      1920: new URL('./trace-public-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./trace-public-640.jpg', import.meta.url).href,
      1280: new URL('./trace-public-1280.jpg', import.meta.url).href,
      1920: new URL('./trace-public-1920.jpg', import.meta.url).href,
    },
  },
  'team': {
    key: 'team',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./team-640.avif', import.meta.url).href,
      1280: new URL('./team-1280.avif', import.meta.url).href,
      1920: new URL('./team-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./team-640.webp', import.meta.url).href,
      1280: new URL('./team-1280.webp', import.meta.url).href,
      1920: new URL('./team-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./team-640.jpg', import.meta.url).href,
      1280: new URL('./team-1280.jpg', import.meta.url).href,
      1920: new URL('./team-1920.jpg', import.meta.url).href,
    },
  },
  'import': {
    key: 'import',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./import-640.avif', import.meta.url).href,
      1280: new URL('./import-1280.avif', import.meta.url).href,
      1920: new URL('./import-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./import-640.webp', import.meta.url).href,
      1280: new URL('./import-1280.webp', import.meta.url).href,
      1920: new URL('./import-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./import-640.jpg', import.meta.url).href,
      1280: new URL('./import-1280.jpg', import.meta.url).href,
      1920: new URL('./import-1920.jpg', import.meta.url).href,
    },
  },
  'notifications': {
    key: 'notifications',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./notifications-640.avif', import.meta.url).href,
      1280: new URL('./notifications-1280.avif', import.meta.url).href,
      1920: new URL('./notifications-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./notifications-640.webp', import.meta.url).href,
      1280: new URL('./notifications-1280.webp', import.meta.url).href,
      1920: new URL('./notifications-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./notifications-640.jpg', import.meta.url).href,
      1280: new URL('./notifications-1280.jpg', import.meta.url).href,
      1920: new URL('./notifications-1920.jpg', import.meta.url).href,
    },
  },
  'settings': {
    key: 'settings',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./settings-640.avif', import.meta.url).href,
      1280: new URL('./settings-1280.avif', import.meta.url).href,
      1920: new URL('./settings-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./settings-640.webp', import.meta.url).href,
      1280: new URL('./settings-1280.webp', import.meta.url).href,
      1920: new URL('./settings-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./settings-640.jpg', import.meta.url).href,
      1280: new URL('./settings-1280.jpg', import.meta.url).href,
      1920: new URL('./settings-1920.jpg', import.meta.url).href,
    },
  },
  'default': {
    key: 'default',
    objectPosition: 'center center',
    placeholder: true,
    avif: {
      640: new URL('./default-640.avif', import.meta.url).href,
      1280: new URL('./default-1280.avif', import.meta.url).href,
      1920: new URL('./default-1920.avif', import.meta.url).href,
    },
    webp: {
      640: new URL('./default-640.webp', import.meta.url).href,
      1280: new URL('./default-1280.webp', import.meta.url).href,
      1920: new URL('./default-1920.webp', import.meta.url).href,
    },
    jpg: {
      640: new URL('./default-640.jpg', import.meta.url).href,
      1280: new URL('./default-1280.jpg', import.meta.url).href,
      1920: new URL('./default-1920.jpg', import.meta.url).href,
    },
  },
};
