package com.tracex.exception;

public enum ErrorCode {
    AUTH_NO_TOKEN,
    AUTH_INVALID_TOKEN,
    AUTH_SESSION_REVOKED,
    AUTH_ACCOUNT_DELETED,
    AUTH_ACCOUNT_INACTIVE,
    RBAC_INSUFFICIENT,
    NOT_FOUND,
    CONFLICT,
    DISPATCH_OUT_OF_ORDER,
    DISPATCH_EXPIRED,
    BATCH_EXPIRED,
    QUALITY_HOLD,
    VALIDATION_ERROR,
    METHOD_NOT_ALLOWED,
    RATE_LIMITED,
    AI_UNAVAILABLE,
    INTERNAL_ERROR,
    LAST_SUPERADMIN,
    SELF_MODIFICATION_NOT_ALLOWED
}
